[package]
name = "archiveundo"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
fs_extra = "1.3"
dirs = "5.0"
anyhow = "1.0"

[[bin]]
name = "archive"
path = "src/bin/archive.rs"

[[bin]]
name = "undo"
path = "src/bin/undo.rs"
